# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be56a276db090d798493bf3444f81935f10e0d49bf3bf0b7dcd2c84fa0db14263c1b530c9b7f53e2c49f839fa5b3419aae1b66517401c2fd9520d5eb41af2895

test:
  secret_key_base: 3fc612f017ff9d6e23c411adb1c134ec10141c790b4a946d33bbaf244fbe809e37138731690a637d3bbb97eabd840a59cd401cf03988607ea2aa88ab07e13ab9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
